Flesh out `build-npm-modules` just a bit.

diff --git a/scripts/lib/build-npm-modules b/scripts/lib/build-npm-modules
--- a/scripts/lib/build-npm-modules
+++ b/scripts/lib/build-npm-modules
@@ -23,6 +23,14 @@ function init-prog {
 }
 init-prog
 
+# Move `baseDir` and `prodDir` up one layer (not done above because the above is
+# boilerplate).
+progDir="${baseDir}"
+baseDir="$(cd "${baseDir}/.."; /bin/pwd -P)"
+
+# Pull in the build system helper library.
+. "${progDir}/lib/include-build.sh"
+
 
 #
 # Argument parsing
@@ -34,11 +42,11 @@ argError=0
 # Need help?
 showHelp=0
 
-# Options to pass to `out-dir-setup`.
+# Options to pass to `set-up-out`.
 outOpts=()
 
-# Extra options passed to the command.
-extraOpts=()
+# Path to the product info file.
+productInfoPath=''
 
 while true; do
     case $1 in
@@ -46,9 +54,14 @@ while true; do
             showHelp=1
             break
             ;;
+        --clean)
+            outOpts+=("$1")
+            ;;
         --out=?*)
             outOpts+=("$1")
-            extraOpts+=("$1")
+            ;;
+        --product-info=?*)
+            productInfoPath="${1#*=}"
             ;;
         --) # End of all options
             shift
@@ -66,14 +79,24 @@ while true; do
     shift
 done
 
+if [[ ${productInfoPath} == '' ]]; then
+    echo 'Missing required option: --product-info' 1>&2
+    argError=1
+fi
+
 if (( ${showHelp} || ${argError} )); then
     echo 'Usage:'
     echo ''
     echo "${progName} [<opt> ...]"
     echo '  Convert modules into publication form.'
     echo ''
+    echo '  --clean'
+    echo '    Start from a clean build.'
     echo '  --out=<dir>'
-    echo '    Directory where built output goes and also where the module sources are found.'
+    echo '    Directory where built output goes and also where the module sources are'
+    echo '    found.'
+    echo '  --product-info=<path>'
+    echo '    Filesystem path to the product info file. This "option" must be included.'
     echo ''
     echo "${progName} [--help | -h]"
     echo '  Display this message.'
@@ -85,10 +108,37 @@ fi
 # Helper functions
 #
 
+# Determines the product version from the info file.
+function product-version {
+    if [[ ! (-r ${productInfoPath} && -f ${productInfoPath}) ]]; then
+        echo "Not readable: ${productInfoPath}" 1>&2
+        return 1
+    fi
+
+    local line="$(grep '^ *version *=' < "${productInfoPath}")"
+
+    if [[ ${line} =~ ^\ *version\ *=\ *([^\ ]*) ]]; then
+        echo "${BASH_REMATCH[1]}"
+    else
+        echo "Could not determine product version." 1>&2
+        return 1
+    fi
+}
+
 
 #
 # Main script
 #
 
-echo 'TODO!'
+set-up-out "${outOpts[@]}" || exit 1
+
+productVersion="$(product-version)"
+if [[ $? != 0 ]]; then
+    exit 1
+fi
+
+for name in $(local-module-names); do
+    echo "TODO!!! ${name}"
+done
+
 exit 1
