Teach `build-npm-modules` how to publish, too.

diff --git a/scripts/lib/build-npm-modules b/scripts/lib/build-npm-modules
--- a/scripts/lib/build-npm-modules
+++ b/scripts/lib/build-npm-modules
@@ -5,7 +5,7 @@
 # Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
 #
 # Converts the module sources in `out` into a form which is appropriate to hand
-# off to `npm publish`.
+# off to `npm publish`, and optionally also actually publishes them.
 #
 
 # Set `progName` to the program name, `progDir` to its directory, and `baseDir`
@@ -51,6 +51,12 @@ packageBaseJson='{}'
 # Path to the product info file.
 productInfoPath="${baseDir}/product-info.txt"
 
+# Publish?
+publish=0
+
+# Extra options to pass to `npm publish`.
+publishOpts=()
+
 # List of rescopings to do.
 rescopes=()
 
@@ -60,6 +66,9 @@ while true; do
             showHelp=1
             break
             ;;
+        --dry-run|--verbose)
+            publishOpts+=("$1")
+            ;;
         --out=?*)
             outOpts+=("$1")
             ;;
@@ -68,6 +77,9 @@ while true; do
             ;;
         --product-info=?*)
             productInfoPath="${1#*=}"
+            ;;
+        --publish)
+            publish=1
             ;;
         --rescope=?*)
             rescopes+=("${1#*=}")
@@ -97,8 +109,10 @@ if (( ${showHelp} || ${argError} )); then
     echo 'Usage:'
     echo ''
     echo "${progName} [<opt> ...]"
-    echo '  Convert modules into publication form.'
+    echo '  Convert modules into publication form, and optionally publish them.'
     echo ''
+    echo '  --dry-run'
+    echo '    Passed through to `npm publish` when using `--publish`.'
     echo '  --out=<dir>'
     echo '    Directory where built output goes and also where the module sources are'
     echo '    found.'
@@ -107,10 +121,14 @@ if (( ${showHelp} || ${argError} )); then
     echo '    minimal defaults will be used.'
     echo '  --product-info=<path>'
     echo '    Filesystem path to the product info file.'
+    echo '  --publish'
+    echo '    Actually publish the converted modules, using `npm publish`.'
     echo '  --rescope=@<original>:@<new>[/<prefix>]'
     echo '    Translate the indicated module scope in the originals into a new scope'
     echo '    name and optional module name prefix in the result. Can be specified'
     echo '    more than once.'
+    echo '  --verbose'
+    echo '    Passed through to `npm publish` when using `--publish`.'
     echo ''
     echo "${progName} [--help | -h]"
     echo '  Display this message.'
@@ -321,6 +339,53 @@ function product-version {
     fi
 }
 
+# Publishes all of the constructed modules.
+function publish-modules {
+    echo 'Publishing modules...'
+
+    local publishCount=0
+    local errors=()
+    local plural
+
+    for name in $(publishable-module-names); do
+        echo "${name}"
+
+        (
+            cd "${publishDir}/${name}"
+            npm publish "${publishOpts[@]}"
+        )
+
+        if [[ $? == 0 ]]; then
+            ((publishCount++))
+        else
+            errors+=("${name}")
+        fi
+    done
+
+    plural=''
+    if (( ${publishCount} == 1 )); then
+        plural='s'
+    fi
+    echo ''
+    echo "Published ${publishCount} module${plural}."
+
+    if (( ${#errors[@]} != 0 )); then
+        echo '' 1>&2
+        echo 'Trouble publishing the following:' 1>&2
+
+        for name in "${errors[@]}"; do
+            echo "  ${name}"
+        done
+
+        plural='s'
+        if (( ${#errors[@]} == 1 )); then
+            plural=''
+        fi
+
+        echo "${#errors[@]} error${plural}." 1>&2
+        return 1
+    fi
+}
 
 #
 # Main script
@@ -358,5 +423,9 @@ for name in $(local-module-names); do
     echo "${name}"
     process-module "${name}" || exit 1
 done
+
+if (( ${publish} )); then
+    publish-modules || exit 1
+fi
 
 echo "Done!"
