Verify tool versions as a preflight check before building.

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -112,6 +112,45 @@ fi
 # Helper functions
 #
 
+# Helper for `check-environment-dependencies` which validates one dependency.
+function check-dependency {
+    local name="$1"
+    local versionCmd="$2"
+    local match="$3"
+
+    # Extract just the command name, and verify that it exists at all.
+
+    local cmdName=''
+    if [[ ${versionCmd} =~ ^([^ ]+) ]]; then
+        cmdName="${BASH_REMATCH[1]}"
+    else
+        # **Note:* This indicates a bug in this script, not a problem with the
+        # environment.
+        echo "Could not determine commmand name for ${name}." 1>&2
+        exit 1
+    fi
+
+    if ! which "${cmdName}" >/dev/null 2>&1; then
+        echo "Missing required command for ${name}: ${cmdName}" 1>&2
+        exit 1
+    fi
+
+    local version="$(${versionCmd} 2>&1)"
+    if ! grep -q -e "${match}" <<< "${version}"; then
+        echo "Unsupported version of ${name}: ${version}" 1>&2
+        exit 1
+    fi
+}
+
+# Checks the versions of our various expected-installed dependencies, notably
+# including Node and npm.
+function check-environment-dependencies {
+    check-dependency 'Node' 'node --version' '^v[67]\.'
+    check-dependency 'npm' 'npm --version' '^[34]\.'
+    check-dependency 'jq' 'jq --version' '^jq-1\.'
+    check-dependency 'rsync' 'rsync --version' '.' # No actual version check.
+}
+
 # Sets up the output directory, including cleaning it out or creating it, as
 # necessary.
 function set-up-out {
@@ -441,7 +480,8 @@ if [[ (${boxDir} != '') && ("$(uname)" == 'Darwin') ]]; then
 fi
 
 (
-    set-up-dir-mapping \
+    check-environment-dependencies \
+        && set-up-dir-mapping \
         && copy-sources \
         && fix-packages \
         && build-compiler \
