Factor out common `rsync` options and comments.
...and add a new option to fix a gotcha as noted in the long comment that
goes with it.

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -146,6 +146,26 @@ function check-environment-dependencies {
     check-dependency 'rsync' 'rsync --version' '.' # No actual version check.
 }
 
+# Calls `rsync` so as to do an all-local (not actually remote) "archive" copy
+# (preserving permissions, modtimes, etc.).
+#
+# **Note:** We use `rsync` (even though this is a totally local operation)
+# because it has well-defined behavior when copying a tree on top of another
+# tree and also knows how to create directories as needed.
+#
+# **Note:** Trailing slashes on source directory names are significant to
+# `rsync`. This is salient at some of the use sites.
+function rsync-archive {
+    # **Note:** We turn off file-sameness checking, which is irrelevant for this
+    # use and is furthermore counterproductive, in that it can cause a failure
+    # to copy when two non-identical files happen to match in both size and
+    # timestamp. (This has happened in practice. When running a build on a
+    # freshly checked-out source tree, many many files have the same timestamps,
+    # so only the file sizes come into play, and it's very easy to have a file
+    # size coincidence.)
+    rsync --archive --ignore-times "$@"
+}
+
 # Sets up the output directory, including cleaning it out or creating it, as
 # necessary. This also sets `finalDir` to the directory under `outDir` for the
 # final built product.
@@ -269,16 +289,11 @@ function copy-sources {
         ))
 
         # Copy the first mapped directory entirely, including removing deleted
-        # files. Then copy the rest -- the overlays -- without deleting. We use
-        # `rsync` (even though this is a totally local operation) because it has
-        # well-defined behavior when copying a tree on top of another tree and
-        # also knows how to create directories as needed. Note that trailing
-        # slashes on source directory names are significant to `rsync`
-        # semantics.
+        # files. Then copy the rest -- the overlays -- without deleting.
         sources=($(cat "${mapFile}"))
         delArg=(--delete)
         for s in "${sources[@]}"; do
-            rsync --archive "${delArg[@]}" "${excludes[@]}" "${s}/" "${dir}"
+            rsync-archive "${delArg[@]}" "${excludes[@]}" "${s}/" "${dir}"
             delArg=()
         done
     done
@@ -324,7 +339,7 @@ function do-install {
 
     rm -rf "${npmDir}"
     mkdir -p "${npmDir}"
-    rsync --archive "${packageJson}" "${npmDir}/package.json"
+    rsync-archive "${packageJson}" "${npmDir}/package.json"
 
     if [[ ${boxDir} == '' ]]; then
         # No boxed dependencies. Normal install.
@@ -361,7 +376,7 @@ function do-install {
 
     local d
     for d in $(cd "${npmDir}/node_modules"; /bin/ls -A); do
-        rsync --archive --delete \
+        rsync-archive --delete \
             "${npmDir}/node_modules/${d}" "${toDir}/node_modules" \
             || return 1
     done
@@ -370,7 +385,7 @@ function do-install {
 
     # Copy the `package.json` that we installed with, so we can compare it on
     # subsequent builds.
-    rsync --archive "${packageJson}" "${npmPackageJson}" || return 1
+    rsync-archive "${packageJson}" "${npmPackageJson}" || return 1
 
     echo "${dir}:" 'External dependencies... done.'
 }
@@ -408,11 +423,10 @@ function build-server {
         fi
     done
 
-    # Copy everything else over to the final `server` directory as-is. See above
-    # about why we use `rsync` in general; in addition, in this case we also get
-    # to use the `--update` option to avoid clobbering those Babel-compiled
-    # files we just went through all the trouble to make.
-    rsync --archive --delete --update "${fromDir}/" "${toDir}" || return 1
+    # Copy everything else over to the final `server` directory as-is. We use
+    # the `--update` option to avoid clobbering those Babel-compiled files we
+    # just went through all the trouble to make.
+    rsync-archive --delete --update "${fromDir}/" "${toDir}" || return 1
 }
 
 # Builds the client code.
@@ -422,8 +436,8 @@ function build-client {
     mkdir -p "${toDir}" || return 1
     do-install client || return 1
 
-    # Copy the built result into the final output. See above about `rsync`.
-    rsync --archive --delete "${outDir}/client/" "${toDir}" \
+    # Copy the built result into the final output.
+    rsync-archive --delete "${outDir}/client/" "${toDir}" \
     || return 1
 }
 
@@ -443,8 +457,7 @@ function build-bin {
 
     mkdir -p "${toDir}" || return 1
 
-    # See comment above about why we use `rsync`.
-    rsync --archive --delete --exclude='README.md' \
+    rsync-archive --delete --exclude='README.md' \
         "${baseDir}/etc/bin-src/" "${toDir}" \
         || return 1
 
