Hit the right URI.
Also fix a redirect.

diff --git a/scripts/slurp-heap b/scripts/slurp-heap
--- a/scripts/slurp-heap
+++ b/scripts/slurp-heap
@@ -34,6 +34,9 @@ showHelp=0
 # Output file.
 outFile=''
 
+# Monitor server port.
+monitorPort=8888
+
 while true; do
     case $1 in
         -h|--help)
@@ -42,6 +45,9 @@ while true; do
             ;;
         --out=?*)
             outFile="${1#*=}"
+            ;;
+        --port=?*)
+            monitorPort="${1#*=}"
             ;;
         --) # End of all options
             shift
@@ -71,7 +77,9 @@ if (( ${showHelp} || ${argError} )); then
     echo ''
     echo "${progName} [<opt> ...] <hostname>"
     echo '  Induces a heap dump on a given server and grabs it into a file on'
-    echo '  the local machine.'
+    echo '  the local machine. This is achieved by `ssh`ing to the host (and'
+    echo '  not, e.g., `curl`ing to it), on the assumption that the monitor'
+    echo '  port is often not exposed to an external network interface.'
     echo ''
     echo '  --out=<file>'
     echo '    Where to store the heap dump. If this is not specified, it'
@@ -79,11 +87,27 @@ if (( ${showHelp} || ${argError} )); then
     echo '    specified and does not end with `.heapsnapshot` then that suffix'
     echo '    will get automatically appended, since Chrome Devtools only'
     echo '    recognizes heap dumps with that suffix as such.'
+    echo '  --port=<port-num>'
+    echo '    What port to use as the application monitor port.'
     echo ''
     echo "${progName} [--help | -h]"
     echo '  Display this message.'
     exit ${argError}
 fi
+
+
+#
+# Helper functions
+#
+
+# Cleanup function to kill the `ssh` process upon process termination.
+function kill-ssh {
+    trap - SIGTERM # Avoid recursion.
+    kill -9 "${sshPid}"
+
+    exit
+}
+
 
 #
 # Main script
@@ -97,5 +121,29 @@ if [[ ! ${outFile} =~ '.heapsnapshot'$ ]]; then
     outFile+='.heapsnapshot'
 fi
 
-echo "Grabbing heap snapshot into ${outFile}..."
-# TODO: Finish this.
+echo "Grabbing heap snapshot from ${hostname} into ${outFile}..."
+
+# What's going on: This sets up a ssh-based port forward from the local machine
+# to the application monitor port on the server. We use an arbitrary port number
+# on the local side, just because being dynamic is more trouble than it's worth.
+
+localPort=58888
+set +m
+ssh -N -L "localhost:${localPort}:localhost:${monitorPort}" "${hostname}" &
+if (( $? )); then
+    exit $?
+fi
+set -m
+sshPid="$!"
+
+# Wait a moment, and exit if the `ssh` command seems to have failed.
+sleep 5
+if ! ps -p "${sshPid}" >/dev/null 2>&1; then
+    exit 1
+fi
+
+trap kill-ssh SIGINT SIGTERM EXIT
+
+# Actually do the dump!
+
+curl -o "${outFile}" "http://localhost:${localPort}/heapdump"
